#!/usr/bin/env bash

[[ -n $SERVER_NAME_BASE ]] || SERVER_NAME_BASE="Tron Server"

if [[ -z $SERVER_NUM ]]
then 
  echo "SERVER_NUM not set"
  exit 1
fi

if [[ -z $NETWORK ]]
then
  echo "NETWORK not set - we need an ipvlan or macvlan docker network to give LAN broadcast access"
  exit 1
fi 

mkdir -p gamedata/server$SERVER_NUM/var

docker run -it --net=$NETWORK --restart=unless-stopped -e "SERVER_NAME=$SERVER_NAME_BASE $SERVER_NUM" -v `pwd`/gamedata/server$SERVER_NUM/var:/tron/server/var armagetron
